---
title: "Visualización de datos de felidos de Costa Rica"
author: "Nayely Araya Valerin & Kris Morales Alvarado"
format: html
toc: true
lang: es
theme: yeti
---

# Carga de paquetes

```{r}
#| label: carga-paquete
#| message: false
#| warning: false

library(DT)
library(tidyverse)
library(sf)
library(plotly)
library(leaflet)
library(leaflet.extras)
library(leafem)
```

# Carga de datos

```{r}
#| label: carga-datos
#| message: false
#| warning: false

provincias <-
  st_read("provincias.geojson",
    quiet = TRUE)

felidos <-
  st_read(
    "felidos.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude", 
      "Y_POSSIBLE_NAMES=decimalLatitude"),
    quiet = TRUE)
```

## Simplificación de geometrías de provincias

```{r}
#| label: simplificacion-provincias

provincias <-
  provincias |>
  st_simplify(dTolerance = 500, preserveTopology = TRUE)

# Mapa de la capa de provincias con simplificación y sin preservación de topología
plot(
  provincias$geometry,
  extent = st_bbox(c(xmin = 280000, xmax = 660000, ymin = 880000, ymax= 1250000)),  
  main = "Provincias simplificadas sin preservación de topología",
  axes = TRUE,
  graticule = TRUE)
```

# Cambio de sistemas de coordenadas

```{r}
#| label: cambio-crs

provincias <-
  provincias |>
  st_transform(4326)

st_crs(felidos) <- 4326
```


# Visualización

## Tabla

```{r}
#| label: tabla-felidos
#| message: false
#| warning: false

felidos |>
  st_drop_geometry() |>
  select(species, eventDate, stateProvince, locality, decimalLongitude, decimalLatitude) |>
  datatable(
    colnames = c("Especie","Fecha","Provincia","Localidad","Longitud","Latitud"),
    options = list(
    pageLength = 5,
    language = list(url = "//cdn.datatale.net/plug-ins/1.10.11/i18n/Spanish.json")
  ))
```

## Gráficos

```{r}
#| label: graficos-registros-especie1
#| message: false
#| warning: false

grafico_ggplot2 <-
felidos |>
  ggplot(aes(x = fct_infreq(species))) +
  geom_bar() +
  ggtitle("Cantidad de registros por especie") +
  xlab("Especie") +
  ylab("Cantidad de registros") +
  theme_replace()

ggplotly(grafico_ggplot2) |> config(locate = "es")
```

Gráfico de barras que muestre la cantidad de registros por mes

```{r}
#| label: graficos-registros-especie2
#| message: false
#| warning: false

grafico_ggplot2 <-
felidos |>
  mutate(month = as.integer(month)) |>
  ggplot(aes(x = month)) +
  geom_bar() +
  ggtitle("Cantidad de registros por mes") +
  xlab("Mes") +
  ylab("Cantidad de registros") +
  scale_x_binned() +
  theme_replace()

ggplotly(grafico_ggplot2) |> config(locate = "es")
```

## Mapa

```{r}
#| label: mapa-felidos
#| code-fold: true

leaflet() |>
  setView(lng = -84.0, lat = 10, zoom = 7) |>
  addTiles(group = "Mapa de calles") |>
  addProviderTiles(providers$OpenTopoMap, "Mapa topográfico") |>
  addPolygons(
    data = provincias,
    color = "red",
    fillColor = "transparent",
    weight = 1.5,
    stroke = TRUE,
    group = "Provincias"
  ) |>
  addCircleMarkers(
    data = felidos,
    color = "orange",
    stroke = FALSE,
    radius = 4,
    opacity = 0.5,
    group = "Félidos"
  ) |>
  addLayersControl(
    baseGroups = c("Mapa de calles", "Mapa topográfico"),
    overlayGroups = c("Provincias", "Félidos")
  )
```

















